(function(){var a="undefined"!==typeof window&&"undefined"!==typeof window.document?window.document:{},e="undefined"!==typeof module&&module.exports,d="undefined"!==typeof Element&&"ALLOW_KEYBOARD_INPUT"in Element,b=function(){for(var b,c=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),
"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],d=0,e=c.length,g={};d<e;d++)if((b=c[d])&&b[1]in a){for(d=0;d<b.length;d++)g[c[0][d]]=
b[d];return g}return!1}(),c={change:b.fullscreenchange,error:b.fullscreenerror},g={request:function(c){var f=b.requestFullscreen;c=c||a.documentElement;if(/5\.1[.\d]* Safari/.test(navigator.userAgent))c[f]();else c[f](d&&Element.ALLOW_KEYBOARD_INPUT)},exit:function(){a[b.exitFullscreen]()},toggle:function(a){this.isFullscreen?this.exit():this.request(a)},onchange:function(a){this.on("change",a)},onerror:function(a){this.on("error",a)},on:function(b,d){var f=c[b];f&&a.addEventListener(f,d,!1)},off:function(b,
d){var f=c[b];f&&a.removeEventListener(f,d,!1)},raw:b};b?(Object.defineProperties(g,{isFullscreen:{get:function(){return!!a[b.fullscreenElement]}},element:{enumerable:!0,get:function(){return a[b.fullscreenElement]}},enabled:{enumerable:!0,get:function(){return!!a[b.fullscreenEnabled]}}}),e?module.exports=g:window.screenfull=g):e?module.exports=!1:window.screenfull=!1})();var s_iScaleFactor=1,s_bIsIphone=!1,s_iOffsetX,s_iOffsetY;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isChrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}function isIOS(){var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");for(-1!==navigator.userAgent.toLowerCase().indexOf("iphone")&&(s_bIsIphone=!0);a.length;)if(navigator.platform===a.pop())return!0;return s_bIsIphone=!1}
window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function getSize(a){var e=a.toLowerCase(),d=window.document,b=d.documentElement;if(void 0===window["inner"+a])a=b["client"+a];else if(window["inner"+a]!=b["client"+a]){var c=d.createElement("body");c.id="vpw-test-b";c.style.cssText="overflow:scroll";var g=d.createElement("div");g.id="vpw-test-d";g.style.cssText="position:absolute;top:-1000px";g.innerHTML="<style>@media("+e+":"+b["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+e+":7px!important}}</style>";c.appendChild(g);b.insertBefore(c,d.head);
a=7==g["offset"+a]?b["client"+a]:window["inner"+a];b.removeChild(c)}else a=window["inner"+a];return a}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var e=getSize("Width");_checkOrientation(e,a);var d=Math.min(a/CANVAS_HEIGHT,e/CANVAS_WIDTH),b=CANVAS_WIDTH*d,d=CANVAS_HEIGHT*d;if(d<a){var c=a-d;d+=c;b+=CANVAS_WIDTH/CANVAS_HEIGHT*c}else b<e&&(c=e-b,b+=c,d+=CANVAS_HEIGHT/CANVAS_WIDTH*c);c=a/2-d/2;var g=e/2-b/2,f=CANVAS_WIDTH/b;if(g*f<-EDGEBOARD_X||c*f<-EDGEBOARD_Y)d=Math.min(a/(CANVAS_HEIGHT-2*
EDGEBOARD_Y),e/(CANVAS_WIDTH-2*EDGEBOARD_X)),b=CANVAS_WIDTH*d,d*=CANVAS_HEIGHT,c=(a-d)/2,g=(e-b)/2,f=CANVAS_WIDTH/b;s_iOffsetX=-1*g*f;s_iOffsetY=-1*c*f;0<=c&&(s_iOffsetY=0);0<=g&&(s_iOffsetX=0);null!==s_oGame&&s_oGame.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsIphone?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*b,s_oStage.canvas.height=2*d,canvas.style.width=b+"px",canvas.style.height=d+"px",s_oStage.scaleX=s_oStage.scaleY=
2*Math.min(b/CANVAS_WIDTH,d/CANVAS_HEIGHT)):s_bMobile||isChrome()?($("#canvas").css("width",b+"px"),$("#canvas").css("height",d+"px")):(s_oStage.canvas.width=b,s_oStage.canvas.height=d,s_iScaleFactor=Math.min(b/CANVAS_WIDTH,d/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>c?$("#canvas").css("top",c+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",g+"px");fullscreenHandler()}}
function _checkOrientation(a,e){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>e?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function inIframe(){try{return window.self!==window.top}catch(a){return!0}}function createBitmap(a,e,d){var b=new createjs.Bitmap(a),c=new createjs.Shape;e&&d?c.graphics.beginFill("#fff").drawRect(0,0,e,d):c.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);b.hitArea=c;return b}function createSprite(a,e,d,b,c,g){a=null!==e?new createjs.Sprite(a,e):new createjs.Sprite(a);e=new createjs.Shape;e.graphics.beginFill("#000000").drawRect(-d,-b,c,g);a.hitArea=e;return a}
function randomFloatBetween(a,e,d){"undefined"===typeof d&&(d=2);return parseFloat(Math.min(a+Math.random()*(e-a),e).toFixed(d))}function shuffle(a){for(var e=a.length,d,b;0!==e;)b=Math.floor(Math.random()*e),--e,d=a[e],a[e]=a[b],a[b]=d;return a}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var e=document.createEvent("MouseEvents");e.initEvent("click",!0,!0);a.dispatchEvent(e)}}};function playSound(a,e,d){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(e),s_aSounds[a].loop(d),s_aSounds[a]):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}
function setVolume(a,e){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(e)}function setMute(a,e){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(e)}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}function getParamValue(a){for(var e=window.location.search.substring(1).split("&"),d=0;d<e.length;d++){var b=e[d].split("=");if(b[0]==a)return b[1]}}
(function(){function a(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in b?document.body.className=b[a.type]:(document.body.className=this[e]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var e="hidden";e in document?document.addEventListener("visibilitychange",a):(e="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(e="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(e="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();
function fullscreenHandler(){ENABLE_FULLSCREEN&&(s_bFullscreen=screen.height<window.innerHeight+3&&screen.height>window.innerHeight-3?!0:!1,null!==s_oGame&&s_oGame.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut())}if(screenfull.enabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oGame&&s_oGame.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut()});
function CSpriteLibrary(){var a,e,d,b,c,g;this.init=function(f,l,k){d=e=0;b=f;c=l;g=k;a={}};this.addSprite=function(b,c){a.hasOwnProperty(b)||(a[b]={szPath:c,oSprite:new Image},e++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){c.call(g)};this._onSpriteLoaded=function(){b.call(g);++d==e&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return e}}
var CANVAS_WIDTH=1600,CANVAS_HEIGHT=768,EDGEBOARD_X=288,EDGEBOARD_Y=0,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,FONT_GAME="arialbold",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,HOOK_START_X=CANVAS_WIDTH/2,HOOK_START_Y=64,STATE_HOOK_ROTATE=0,STATE_HOOK_MOVE=1,STATE_HOOK_MOVE_BACK=2,MALUS_SCORE,HOOK_SPEED,LEVEL_TIME,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION;TEXT_SCORE="SCORE";TEXT_LEVEL="LEVEL";
TEXT_GAME_OVER="GAME OVER";TEXT_WIN="CONGRATULATIONS";TEXT_TARGET="TARGET";TEXT_COLLECT="COLLECT";TEXT_AVOID="AVOID";TEXT_PLAY="PLAY";TEXT_EXIT="EXIT";TEXT_PASSED="PASSED";var TEXT_DEVELOPED="developed by";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better?";
function CGfxButton(a,e,d,b){var c,g,f;this._init=function(a,b,d,e){c=[];g=[];f=createBitmap(d);f.x=a;f.y=b;f.regX=d.width/2;f.regY=d.height/2;f.cursor="pointer";e&&s_oStage.addChild(f);this._initListener()};this.unload=function(){f.off("mousedown");f.off("pressup");s_oStage.removeChild(f)};this.setVisible=function(a){f.visible=a};this._initListener=function(){oParent=this;f.on("mousedown",this.buttonDown);f.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){c[a]=b;g[a]=d};this.buttonRelease=
function(){f.scaleX=1;f.scaleY=1;playSound("click",1,!1);c[ON_MOUSE_UP]&&c[ON_MOUSE_UP].call(g[ON_MOUSE_UP])};this.buttonDown=function(){f.scaleX=.9;f.scaleY=.9;c[ON_MOUSE_DOWN]&&c[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN])};this.setPosition=function(a,b){f.x=a;f.y=b};this.setX=function(a){f.x=a};this.setY=function(a){f.y=a};this.getButtonImage=function(){return f};this.getX=function(){return f.x};this.getY=function(){return f.y};this._init(a,e,d,b);return this}
function CTextButton(a,e,d,b,c,g,f){var l,k,h;this._init=function(a,b,c,d,e,f,g){l=[];k=[];var t=createBitmap(c),u=Math.ceil(g/20),m=new createjs.Text(d,g+"px "+e,"#000000");m.textAlign="center";var q=m.getBounds();m.x=c.width/2+u;m.y=(c.height-q.height)/2+u;d=new createjs.Text(d,g+"px "+e,f);d.textAlign="center";q=d.getBounds();d.x=c.width/2;d.y=(c.height-q.height)/2;h=new createjs.Container;h.x=a;h.y=b;h.regX=c.width/2;h.regY=c.height/2;h.cursor="pointer";h.addChild(t,m,d);s_oStage.addChild(h);
this._initListener()};this.unload=function(){h.off("mousedown");h.off("pressup")};this.setVisible=function(a){h.visible=a};this._initListener=function(){oParent=this;h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){l[a]=b;k[a]=c};this.buttonRelease=function(){h.scaleX=1;h.scaleY=1;playSound("click",1,!1);l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(k[ON_MOUSE_UP])};this.buttonDown=function(){h.scaleX=.9;h.scaleY=.9;l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};
this.setPosition=function(a,b){h.x=a;h.y=b};this.setX=function(a){h.x=a};this.setY=function(a){h.y=a};this.getButtonImage=function(){return h};this.getX=function(){return h.x};this.getY=function(){return h.y};this._init(a,e,d,b,c,g,f);return this}
function CToggle(a,e,d,b,c){var g,f,l,k,h;this._init=function(a,b,c,d){l=[];k=[];var e=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});f=d;g=!1;h=createSprite(e,"state_"+f,c.width/2/2,c.height/2,c.width/2,c.height);h.x=a;h.y=b;h.stop();t.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);s_bMobile||h.off("mouseover",
this.buttonOver);t.removeChild(h)};this._initListener=function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease);if(!s_bMobile)h.on("mouseover",this.buttonOver)};this.addEventListener=function(a,b,c){l[a]=b;k[a]=c};this.setActive=function(a){f=a;h.gotoAndStop("state_"+f)};this.enable=function(){g=!1};this.disable=function(){g=!0};this.buttonRelease=function(){g||(h.scaleX=1,h.scaleY=1,playSound("click",1,!1),f=!f,h.gotoAndStop("state_"+f),l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(k[ON_MOUSE_UP],
f))};this.buttonDown=function(){g||(h.scaleX=.9,h.scaleY=.9,l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN]))};this.buttonOver=function(a){g||s_bMobile||(a.target.cursor="pointer")};this.setPosition=function(a,b){h.x=a;h.y=b};var t=c;this._init(a,e,d,b)}
function CPreloader(){var a,e,d,b,c,g,f;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();f=new createjs.Container;s_oStage.addChild(f)};this.unload=function(){f.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(g).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var l=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));f.addChild(l);l=s_oSpriteLibrary.getSprite("progress_bar");b=createBitmap(l);b.x=CANVAS_WIDTH/2-l.width/2;b.y=CANVAS_HEIGHT-70;f.addChild(b);a=l.width;e=l.height;c=new createjs.Shape;c.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(b.x,b.y,1,e);f.addChild(c);b.mask=
c;d=new createjs.Text("","30px "+FONT_GAME,"#fff");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT-70;d.shadow=new createjs.Shadow("#000",2,2,2);d.textBaseline="alphabetic";d.textAlign="center";f.addChild(d);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;f.addChild(g)};this.refreshLoader=function(f){d.text=f+"%";c.graphics.clear();f=Math.floor(f*a/100);c.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(b.x,b.y,f,e)};this._init()}
function CMain(a){var e=!1,d=0,b,c=STATE_LOADING,g,f;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;g=new CPreloader};this._initSounds=function(){var a=[];a.push({path:"./sounds/",filename:"explosion",loop:!1,volume:1,ingamename:"explosion"});a.push({path:"./sounds/",filename:"click",loop:!1,volume:1,ingamename:"click"});a.push({path:"./sounds/",filename:"game_over",loop:!1,volume:1,ingamename:"game_over"});a.push({path:"./sounds/",filename:"bonus",loop:!1,volume:1,ingamename:"bonus"});a.push({path:"./sounds/",filename:"win",loop:!1,volume:1,ingamename:"win"});
a.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});b+=a.length;s_aSounds=[];for(var c=0;c<a.length;c++)s_aSounds[a[c].ingamename]=new Howl({src:[a[c].path+a[c].filename+".mp3",a[c].path+a[c].filename+".ogg"],autoplay:!1,preload:!0,loop:a[c].loop,volume:a[c].volume,onload:s_oMain.handleFileLoad()})};this._loadImages=function(){s_oSpriteLibrary.init(this.handleFileLoad,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");
s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("hook","./sprites/hook.png");s_oSpriteLibrary.addSprite("nugget_1","./sprites/nugget_1.png");s_oSpriteLibrary.addSprite("nugget_2","./sprites/nugget_2.png");s_oSpriteLibrary.addSprite("nugget_3","./sprites/nugget_3.png");s_oSpriteLibrary.addSprite("nugget_4",
"./sprites/nugget_4.png");s_oSpriteLibrary.addSprite("malus","./sprites/malus.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("clock","./sprites/clock.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("ctl_logo","./sprites/ctl_logo.png");b=s_oSpriteLibrary.getNumSprites();
s_oSpriteLibrary.loadSprites()};this.handleFileLoad=function(){d++;g.refreshLoader(Math.floor(d/b*100));d===b&&this._allResourcesLoaded()};this._onAllImagesLoaded=function(){};this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();e=!0};this._allResourcesLoaded=function(){g.unload();isIOS()||(s_oSoundTrack=playSound("soundtrack",1,!0));s_oMain.gotoMenu()};this.gotoMenu=function(){new CMenu;c=STATE_MENU};this.gotoGame=function(){f=new CGame(l);
c=STATE_GAME};this.gotoHelp=function(){new CHelp;c=STATE_HELP};this.stopUpdate=function(){e=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();e=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this._update=function(){if(e){var a=(new Date).getTime();s_iTimeElaps=a-
s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=a;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);c===STATE_GAME&&f.update();s_oStage.update()}};s_oMain=this;var l=a;ENABLE_FULLSCREEN=a.fullscreen;ENABLE_CHECK_ORIENTATION=a.check_orientation;this.initContainer()}var s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_bAudioActive=!0,s_oSoundTrack=null,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_bFullscreen=!1,s_aSounds;
function CMenu(){var a,e,d,b,c,g,f,l,k,h,t,u,q=null,w=null,n;this._init=function(){l=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(l);var m=s_oSpriteLibrary.getSprite("but_play");c=CANVAS_HEIGHT/2-20;k=new CTextButton(488,c,m,TEXT_PLAY,FONT_GAME,"#ffffff",44);k.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m=s_oSpriteLibrary.getSprite("audio_icon"),g=CANVAS_WIDTH-60,f=60,h=new CToggle(g,f,m,s_bAudioActive,s_oStage),h.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);m=s_oSpriteLibrary.getSprite("but_credits");d=m.height/2+10;b=m.height/2+10;t=new CGfxButton(d,b,m,s_oStage);t.addEventListener(ON_MOUSE_UP,this._onButCreditRelease,this);m=window.document;var p=m.documentElement;q=p.requestFullscreen||p.mozRequestFullScreen||p.webkitRequestFullScreen||p.msRequestFullscreen;w=m.exitFullscreen||m.mozCancelFullScreen||m.webkitExitFullscreen||m.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(q=!1);q&&!1===inIframe()&&(m=s_oSpriteLibrary.getSprite("but_fullscreen"),
a=d+m.width/2+10,e=b,u=new CToggle(a,e,m,s_bFullscreen,s_oStage),u.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));n=new createjs.Shape;n.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(n);createjs.Tween.get(n).to({alpha:0},1E3).call(function(){n.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(c,k){t.setPosition(d+c,k+b);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||h.setPosition(g-c,k+f);q&&!1===inIframe()&&
u.setPosition(a+c,e+k)};this.unload=function(){k.unload();k=null;t.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)h.unload(),h=null;q&&!1===inIframe()&&u.unload();s_oStage.removeAllChildren();s_oMenu=l=null};this.resetFullscreenBut=function(){u.setActive(s_bFullscreen)};this._onButPlayRelease=function(){this.unload();isIOS()&&null===s_oSoundTrack&&(s_oSoundTrack=playSound("soundtrack",1,!0));s_oMain.gotoGame();$(s_oMain).trigger("start_session")};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);
s_bAudioActive=!s_bAudioActive};this._onButCreditRelease=function(){new CCreditsPanel};this._onFullscreenRelease=function(){s_bFullscreen?w.call(window.document):q.call(window.document.documentElement);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CHelp(a){var e,d,b,c,g;this._init=function(a){a=createBitmap(a);b=new createjs.Text(TEXT_COLLECT,"40px "+FONT_GAME,"#000000");b.x=CANVAS_WIDTH/2+2;b.y=242;b.textAlign="center";d=new createjs.Text(TEXT_COLLECT,"40px "+FONT_GAME,"#ffffff");d.x=CANVAS_WIDTH/2;d.y=240;d.textAlign="center";g=new createjs.Text(TEXT_AVOID,"40px "+FONT_GAME,"#000000");g.x=CANVAS_WIDTH/2+2;g.y=422;g.textAlign="center";c=new createjs.Text(TEXT_AVOID,"40px "+FONT_GAME,"#ffffff");c.x=CANVAS_WIDTH/2;c.y=420;c.textAlign=
"center";e=new createjs.Container;e.addChild(a);e.addChild(b);e.addChild(g);e.addChild(d);e.addChild(c);s_oStage.addChild(e);var f=this;e.on("pressup",function(){f._onExit()})};this.unload=function(){var a=this;e.off("pressup",function(){a._onExit()});s_oStage.removeChild(e)};this._onExit=function(){this.unload();s_oGame.onExitHelp()};this._init(a)}
function CGame(a){var e,d,b,c,g,f,l=!1,k,h=null,t,u,q,w,n=0,m=1,p,M,H,r,v,x,z,Q,I,J,N,P,K,E,C,A,F,D,B,O,y,L,G=null,R=null;this._init=function(){this.changeState(STATE_HOOK_ROTATE);y=new CLevelSettings;Q=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(Q);F=new createjs.Text(TEXT_LEVEL+" 1","32px "+FONT_GAME,"#000");F.x=310;F.y=CANVAS_HEIGHT-30;F.textAlign="left";F.textBaseline="alphabetic";s_oStage.addChild(F);E=new createjs.Text(TEXT_LEVEL+" 1","32px "+FONT_GAME,"#fff");E.x=
308;E.y=CANVAS_HEIGHT-32;E.textAlign="left";E.textBaseline="alphabetic";s_oStage.addChild(E);O=createBitmap(s_oSpriteLibrary.getSprite("clock"));O.x=298;O.y=10;s_oStage.addChild(O);D=new createjs.Text(LEVEL_TIME/1E3,"40px "+FONT_GAME,"#000");D.x=380;D.y=57;D.textAlign="center";D.textBaseline="alphabetic";s_oStage.addChild(D);C=new createjs.Text(LEVEL_TIME/1E3,"40px "+FONT_GAME,"#fff");C.x=378;C.y=55;C.textAlign="center";C.textBaseline="alphabetic";s_oStage.addChild(C);w=0;q=.05;u=HOOK_SPEED;H=LEVEL_TIME;
p=y.getLevelTarget(m);_iCurTarget=0;B=new createjs.Text(n+"$/"+p+"$","40px "+FONT_GAME,"#000");B.x=310;B.y=117;B.textAlign="left";B.textBaseline="alphabetic";s_oStage.addChild(B);A=new createjs.Text(n+"$/"+p+"$","40px "+FONT_GAME,"#fff");A.x=308;A.y=115;A.textAlign="left";A.textBaseline="alphabetic";s_oStage.addChild(A);var a=s_oSpriteLibrary.getSprite("hook");x=new CHook(a);this._initNuggets();J=new createjs.Shape;J.graphics.beginFill("yellow").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);J.alpha=.01;
s_oStage.addChild(J);var h=this;J.on("pressup",function(){h._onStartDig()});z=new createjs.Shape;z.graphics.beginFill("red").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);z.alpha=.1;z.visible=!1;s_oStage.addChild(z);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(a=s_oSpriteLibrary.getSprite("audio_icon"),b=CANVAS_WIDTH-170,c=60,K=new CToggle(b,c,a,s_bAudioActive,s_oStage),K.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),a=s_oSpriteLibrary.getSprite("but_fullscreen"),e=b-a.width/2-10,d=c):(a=s_oSpriteLibrary.getSprite("but_fullscreen"),
e=CANVAS_WIDTH-170,d=60);var k=window.document,l=k.documentElement;G=l.requestFullscreen||l.mozRequestFullScreen||l.webkitRequestFullScreen||l.msRequestFullscreen;R=k.exitFullscreen||k.mozCancelFullScreen||k.webkitExitFullscreen||k.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(G=!1);G&&!1===inIframe()&&(L=new CToggle(e,d,a,s_bFullscreen,s_oStage),L.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));a=s_oSpriteLibrary.getSprite("but_exit");g=CANVAS_WIDTH-a.width/2-10;f=10+a.height/2;I=new CGfxButton(g,
f,a,!0);I.addEventListener(ON_MOUSE_UP,this._onExit,this);a=s_oSpriteLibrary.getSprite("bg_help");new CHelp(a);a=s_oSpriteLibrary.getSprite("msg_box");P=new CChangeLevel(a);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(a,h){I.setPosition(g-a,h+f);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||K.setPosition(b-a,h+c);G&&!1===inIframe()&&L.setPosition(e-a,d+h)};this.unload=function(){s_oStage.removeAllChildren();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)K.unload(),K=null;
G&&!1===inIframe()&&L.unload();I.unload();I=null;for(var a=0;a<r.length;a++)r[a].unload();for(a=0;a<v.length;a++)v[a].unload();s_oGame=null};this.resetFullscreenBut=function(){L.setActive(s_bFullscreen)};this._initNuggets=function(){r=[];v=[];for(var a=y.getNuggetPosInLevel(m),b=y.getNuggetInfoInLevel(m),c=0;c<a.length;c++){var d=s_oSpriteLibrary.getSprite("nugget_"+b[c].type),d=new CNugget(a[c].x,a[c].y,b[c].scale,d);r.push(d)}b=s_oSpriteLibrary.getSprite("malus");c=y.getMalusPosInLevel(m);for(d=
0;d<c.length;d++){var e=new CMalus(c[d].x,c[d].y,1,b);v.push(e)}M=a.length};this.changeLevel=function(){for(var a=0;a<r.length;a++)r[a].unload();for(a=0;a<v.length;a++)v[a].unload();w=0;u=HOOK_SPEED;x.reset();q+=.025;H=LEVEL_TIME;r=[];for(var a=y.getNuggetPosInLevel(m),c=y.getNuggetInfoInLevel(m),b=0;b<a.length;b++){var d=s_oSpriteLibrary.getSprite("nugget_"+c[b].type),d=new CNugget(a[b].x,a[b].y,c[b].scale,d);r.push(d)}v=[];c=s_oSpriteLibrary.getSprite("malus");b=y.getMalusPosInLevel(m);for(d=0;d<
b.length;d++){var e=new CMalus(b[d].x,b[d].y,1,c);v.push(e)}M=a.length;this.changeState(STATE_HOOK_ROTATE);l=!0;$(s_oMain).trigger("start_level",m)};this.changeState=function(a){k=a;switch(k){case STATE_HOOK_ROTATE:h?(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||playSound("bonus",1,!1),n+=h.getValue(),B.text=n+"$/"+p+"$",A.text=n+"$/"+p+"$",h.hide(),h=null,M--,0===M&&this._endLevel()):x&&x.reset()}};this._checkCollision=function(a,b){var c=a.getPos(),d=b.getPos(),e=b.getRadius();return Math.sqrt((d.x-
c.x)*(d.x-c.x)+(d.y-c.y)*(d.y-c.y))<e?!0:!1};this.hookOutOfBounds=function(){w=0;this.changeState(STATE_HOOK_MOVE_BACK)};this._endLevel=function(){l=!1;k=-1;$(s_oMain).trigger("end_level",m);n<p?this._gameOver():(m++,m>y.getNumLevels()?this._win():(p=y.getLevelTarget(m),E.text=TEXT_LEVEL+" "+m,F.text=TEXT_LEVEL+" "+m,A.text=n+"$/"+p+"$",B.text=n+"$/"+p+"$",P=new CChangeLevel(s_oSpriteLibrary.getSprite("msg_box")),P.show(m,p)))};this.showHurt=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||playSound("explosion",
1,!1);z.visible=!0;var a=this;createjs.Tween.get(z).to({alpha:.6},400).call(function(){a._resetHurt()})};this._resetHurt=function(){z.visible=!1;z.alpha=.5};this._gameOver=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||playSound("game_over",1,!1);N=new CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));N.show(n,!1)};this._win=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||playSound("win",1,!1);N=new CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));N.show(n,!0)};this._onStartDig=function(){k===
STATE_HOOK_ROTATE&&(t=.0174532925*(x.getRotationDeg()+90),this.changeState(STATE_HOOK_MOVE))};this.onExitHelp=function(){l=!0};this._onExit=function(){$(s_oMain).trigger("end_session");$(s_oMain).trigger("share_event",n);$(s_oMain).trigger("save_score",n);this.unload();s_oMain.gotoMenu()};this._onFullscreenRelease=function(){s_bFullscreen?R.call(window.document):G.call(window.document.documentElement);sizeHandler()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};
this.update=function(){if(!1!==l){H-=s_iTimeElaps;var a=Math.floor(H/1E3);C.text=""+a;D.text=""+a;0>H&&(C.text="0",D.text="0",this._endLevel());switch(k){case STATE_HOOK_ROTATE:x.updateRotation(q);break;case STATE_HOOK_MOVE:x.updateMove();for(a=0;a<r.length;a++)if(r[a].isActive()&&this._checkCollision(x,r[a])){w=Math.floor(r[a].getRadius())/8;h=r[a];this.changeState(STATE_HOOK_MOVE_BACK);break}for(a=0;a<v.length;a++)if(this._checkCollision(x,v[a])){w=0;this.showHurt();this.changeState(STATE_HOOK_MOVE_BACK);
n-=MALUS_SCORE;0>n&&(n=0);A.text=n+"$/"+p+"$";B.text=n+"$/"+p+"$";v[a].unload();v.splice(a,1);break}break;case STATE_HOOK_MOVE_BACK:x.updateMoveBack(w),h&&h.updateMoveBack(u-w,t)}}};s_oGame=this;MALUS_SCORE=a.malus_score;HOOK_SPEED=a.hook_speed;LEVEL_TIME=a.level_time;this._init()}var s_oGame=null;
function CHook(a){var e,d,b,c=HOOK_SPEED,g=0,f={x:0,y:1},l,k,h;this._init=function(a){e=0;k=new createjs.Graphics;k.setStrokeStyle(2);k.beginStroke("#000");k.moveTo(HOOK_START_X,HOOK_START_Y);k.lineTo(HOOK_START_X,HOOK_START_Y+50);l=new createjs.Shape(k);s_oStage.addChild(l);h=createBitmap(a);h.x=HOOK_START_X;h.y=HOOK_START_Y;h.regX=a.width/2;h.regY=0;s_oStage.addChild(h);this._drawLine()};this.reset=function(){g=0;d=HOOK_START_X;b=HOOK_START_Y+50};this.normalize=function(a){var b=Math.sqrt(a.x*a.x+
a.y*a.y);0<b&&(a.x/=b,a.y/=b)};this.rotateVector2D=function(a,b){var c=b.x*-Math.sin(a)+b.y*Math.cos(a);b.x=b.x*Math.cos(a)+b.y*Math.sin(a);b.y=c};this.toDegree=function(a){return 180/Math.PI*a};this._drawLine=function(){var a=Math.sin(e);f.x=0;f.y=1;a*=Math.PI/2*.8;this.rotateVector2D(a,f);this.normalize(f);var c=f.y*(50+g);d=HOOK_START_X+f.x*(50+g);b=HOOK_START_Y+c;k.clear();k.setStrokeStyle(1);k.beginStroke("#000");k.moveTo(HOOK_START_X,HOOK_START_Y);k.lineTo(d,b);h.x=d;h.y=b;h.rotation=-this.toDegree(a)};
this.updateRotation=function(a){e+=a;this._drawLine()};this.updateMove=function(){g+=c;this._drawLine();(h.y>CANVAS_HEIGHT||0>h.x||h.x>CANVAS_WIDTH)&&s_oGame.hookOutOfBounds()};this.updateMoveBack=function(a){g-=c-a;this._drawLine();0>g&&s_oGame.changeState(STATE_HOOK_ROTATE)};this.getPos=function(){return{x:d,y:b}};this.getCurDir=function(){};this.getRotationDeg=function(){return h.rotation};this._init(a)}
function CNugget(a,e,d,b){var c,g,f,l,k;this._init=function(a,b,d,e){c=!0;var h=Math.floor(180*Math.random());k=createBitmap(e);k.x=a;k.y=b;k.rotation=h;k.regX=e.width/2;k.regY=e.height/2;k.scaleX=k.scaleY=d;s_oStage.addChild(k);g=Math.floor(1E3*d);l=d;f=e.width};this.unload=function(){s_oStage.removeChild(k);k=null};this.changePos=function(a,b,d){k.x=a;k.y=b;k.scaleX=k.scaleY=l=d;c=k.visible=!0};this.hide=function(){null!==k&&(c=k.visible=!1)};this.getImage=function(){return k};this.getRadius=function(){return f/
2*l*1};this.getPos=function(){return{x:k.x,y:k.y}};this.getX=function(){return k.x};this.getY=function(){return k.y};this.getWidth=function(){return f};this.getValue=function(){return g};this.isActive=function(){return c};this.updateMoveBack=function(a,b){var c=k.y-a*Math.sin(b);k.x-=a*Math.cos(b);k.y=c};this._init(a,e,d,b)}
function CMalus(a,e,d,b){var c,g;this._init=function(a,b,d,e){g=createBitmap(e);g.x=a;g.y=b;g.scaleX=g.scaleY=d;g.regX=e.width/2;g.regY=e.height/2;s_oStage.addChild(g);c=e.width};this.changePos=function(a,b,c){g.x=a;g.y=b;g.scaleX=g.scaleY=c;g.visible=!0};this.unload=function(){s_oStage.removeChild(g);g=null};this.getPos=function(){return{x:g.x,y:g.y}};this.getRadius=function(){return c/2*d*1};this._init(a,e,d,b)}
function CEndPanel(a){var e,d,b,c,g,f;this._init=function(a){e=createBitmap(a);g=new createjs.Text("","50px "+FONT_GAME,"#000");g.x=CANVAS_WIDTH/2+2;g.y=CANVAS_HEIGHT/2-148;g.textAlign="center";c=new createjs.Text("","50px "+FONT_GAME,"#ffffff");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2-150;c.textAlign="center";b=new createjs.Text("","50px "+FONT_GAME,"#000");b.x=CANVAS_WIDTH/2+2;b.y=CANVAS_HEIGHT/2+42;b.textAlign="center";d=new createjs.Text("","50px "+FONT_GAME,"#ffffff");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/
2+40;d.textAlign="center";f=new createjs.Container;f.alpha=0;f.visible=!1;f.addChild(e,b,d,g,c);s_oStage.addChild(f);var k=this;f.on("pressup",function(){k._onExit()})};this.unload=function(){var a=this;f.off("pressup",function(){a._onExit()})};this.show=function(a,e){e?(g.text=TEXT_WIN,c.text=TEXT_WIN):(g.text=TEXT_GAME_OVER,c.text=TEXT_GAME_OVER);b.text=TEXT_SCORE+": "+a;d.text=TEXT_SCORE+": "+a;f.visible=!0;createjs.Tween.get(f).to({alpha:1},500).call(function(){$(s_oMain).trigger("show_interlevel_ad")});
$(s_oMain).trigger("save_score",a)};this._onExit=function(){s_oGame._onExit()};this._init(a)}
function CChangeLevel(a){var e,d,b,c,g,f;this._init=function(a){e=createBitmap(a);d=new createjs.Text(TEXT_WIN,"50px "+FONT_GAME,"#ffffff");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2-150;d.textAlign="center";b=new createjs.Text("","40px "+FONT_GAME,"#ffffff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2-30;b.textAlign="center";c=new createjs.Text("","30px "+FONT_GAME,"#ffffff");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2+90;c.textAlign="center";g=new createjs.Shape;g.graphics.beginFill("yellow").drawRect(0,0,CANVAS_WIDTH,
CANVAS_HEIGHT);g.alpha=.01;f=new createjs.Container;f.alpha=0;f.visible=!1;f.addChild(e,g,d,b,c);s_oStage.addChild(f);var k=this;g.on("pressup",function(){k._onChangeLevel()})};this.show=function(a,d){b.text=TEXT_LEVEL+" "+a+" "+TEXT_PASSED;c.text=TEXT_TARGET+": "+d+"$";f.visible=!0;createjs.Tween.get(f).to({alpha:1},500).call(function(){1<a&&$(s_oMain).trigger("show_interlevel_ad")})};this._onChangeLevel=function(){var a=this;g.off("pressup",function(){a._onChangeLevel()});s_oStage.removeChild(f);
s_oGame.changeLevel()};this._init(a)}
function CLevelSettings(){var a,e,d,b;this._init=function(){a=[];e=[];d=[];var c=[{x:388,y:470},{x:638,y:250},{x:738,y:350},{x:838,y:550},{x:1058,y:600},{x:1138,y:460},{x:1238,y:680}];a.push(c);c=[{type:1,scale:1},{type:2,scale:.5},{type:2,scale:.5},{type:2,scale:.6},{type:3,scale:.4},{type:3,scale:.7},{type:4,scale:1}];e.push(c);c=[{x:938,y:400}];d.push(c);c=[{x:1048,y:580},{x:368,y:350},{x:738,y:380},{x:438,y:550},{x:1248,y:600},{x:868,y:680},{x:1168,y:370}];a.push(c);c=[{type:1,scale:.5},{type:2,
scale:.6},{type:2,scale:.4},{type:2,scale:.3},{type:3,scale:1},{type:3,scale:.7},{type:4,scale:.8}];e.push(c);c=[{x:608,y:400}];d.push(c);c=[{x:948,y:350},{x:768,y:300},{x:538,y:390},{x:338,y:450},{x:488,y:550},{x:1188,y:500},{x:1038,y:650}];a.push(c);c=[{type:1,scale:.5},{type:2,scale:.6},{type:2,scale:.4},{type:2,scale:.3},{type:3,scale:1},{type:3,scale:.7},{type:4,scale:.8}];e.push(c);c=[{x:1138,y:300}];d.push(c);c=[{x:748,y:550},{x:568,y:600},{x:938,y:390},{x:1038,y:450},{x:1188,y:550},{x:1238,
y:300},{x:1038,y:650}];a.push(c);c=[{type:1,scale:.5},{type:2,scale:.6},{type:2,scale:.4},{type:2,scale:.3},{type:3,scale:1},{type:3,scale:.7},{type:4,scale:.8}];e.push(c);c=[{x:688,y:500}];d.push(c);b=[];b.push(2E3);b.push(7E3);b.push(11E3);b.push(15E3)};this.getNuggetPosInLevel=function(b){return a[b-1]};this.getNuggetInfoInLevel=function(a){return e[a-1]};this.getMalusPosInLevel=function(a){return d[a-1]};this.getLevelTarget=function(a){return b[a-1]};this.getNumLevels=function(){return b.length};
this._init()}
function CCreditsPanel(){var a,e,d;this._init=function(){a=new createjs.Container;s_oStage.addChild(a);var b=s_oSpriteLibrary.getSprite("msg_box"),c=createBitmap(b);c.regX=b.width/2;c.regY=b.height/2;c.on("mousedown",function(){});a.addChild(c);a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2;b=new createjs.Text(TEXT_DEVELOPED," 50px "+FONT_GAME,"#ffffff");b.y=-70;b.textAlign="center";b.textBaseline="middle";b.lineWidth=600;a.addChild(b);b=new createjs.Text("www.codethislab.com"," 35px "+FONT_GAME,"#ffffff");
b.y=50;b.textAlign="center";b.textBaseline="middle";b.lineWidth=600;a.addChild(b);b=s_oSpriteLibrary.getSprite("ctl_logo");d=createBitmap(b);d.on("mousedown",this._onLogoButRelease);d.regX=b.width/2;d.regY=b.height/2;a.addChild(d);b=s_oSpriteLibrary.getSprite("but_exit");e=new CGfxButton(1085,210,b,a);e.addEventListener(ON_MOUSE_UP,this.unload,this)};this.unload=function(){s_oStage.removeChild(void 0);s_oStage.removeChild(a);e.unload();d.off("mousedown",this._onLogoButRelease)};this._onLogoButRelease=
function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._init()};
